aduthabus/aduthabus/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bus.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aduthabus/bus/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'bus'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('login/', views.redirect_to_login, name='redirect_to_login'),
    path('add-data/', views.admin_login, name='admin_login'),
    path('added/', views.add_data, name='add_data'),
    path('login/', views.admin_logout, name='admin_logout'),
    path('table/', views.show_table),
    path('home/', views.home_page),
    path("bus_details/<int:id>/", views.bus_details),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aduthabus/bus/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class AdminModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    admin_username = models.CharField(max_length=50, primary_key=True)
# Create your models here.


class bus_timetable(models.Model):
    bus_name = models.CharField(max_length=45)
    bus_no = models.CharField(max_length=45)
    st_1 = models.CharField(max_length=45)
    t_1 = models.TimeField()
    st_2 = models.CharField(max_length=45, blank=True, null=True)
    t_2 = models.TimeField(blank=True, null=True)
    st_3 = models.CharField(max_length=45, blank=True, null=True)
    t_3 = models.TimeField(blank=True, null=True)
    st_4 = models.CharField(max_length=45, blank=True, null=True)
    t_4 = models.TimeField(blank=True, null=True)
    st_5 = models.CharField(max_length=45, blank=True, null=True)
    t_5 = models.TimeField(blank=True, null=True)
    st_6 = models.CharField(max_length=45, blank=True, null=True)
    t_6 = models.TimeField(blank=True, null=True)

aduthabus/bus/views.py
from django.shortcuts import render
from .models import bus_timetable
from collections import OrderedDict
from django.http import Http404

from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


def home_page(request):

    if request.method == 'POST':

        source = request.POST.get("q_source")
        destination = request.POST.get("q_destination")

        if source == '' or destination == '':
            context = {'unavailable_msg': 'Enter source and destination.'}
            return render(request, "home.html", context)

        return show_table(request, source, destination)

    return render(request, "home.html")


def show_table(request, q_s, q_d, *args, **kargs):
    d = []

    all_roots = bus_timetable.objects.all()

    for o in all_roots:
        got_s = False

        data = OrderedDict([
            (o.st_1, o.t_1),
            (o.st_2, o.t_2),
            (o.st_3, o.t_3),
            (o.st_4, o.t_4),
            (o.st_5, o.t_5),
            (o.st_6, o.t_6),
        ])

        for i, t in data.items():

            if str(i).lower() == str(q_s).lower():
                t_s = t
                got_s = True

            if str(i).lower() == str(q_d).lower() and got_s:
                context = {
                    "b_id": o.id,
                    "b_name": o.bus_name,
                    "s_time": t_s,
                    "r_time": t
                }
                d.append(context)
                got_s = False
                break
    if d:
        d = {"d": d,
         "s": q_s.upper(),
         "r": q_d.upper(),
         }
        return render(request, "show_table.html", d)
    else:
        context = {'unavailable_msg': 'Invalid Source/Destination.'}
        return render(request, "home.html", context)



    
# Create your views here.


def bus_details(request, id, *args, **kargs):
    try:
        bus = bus_timetable.objects.get(id=id)
    except bus_timetable.DoesNotExist:
        raise Http404
    context = {"bus": bus}
    return render(request, "bus_details.html", context)


def redirect_to_login(request):
    return render(request, 'login.html')


def admin_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            return render(request, 'add_data.html')
        else:
            return render(request, 'login.html',{"message": "Invalid UserName or Password"})
    else:
        return render(request, 'login.html')


@login_required
def add_data(request):
    context = {}
    if request.method == 'POST':
        bus_name = request.POST.get('bus_name')
        bus_number = request.POST.get('bus_number')

        station1 = request.POST.get('station1')
        time1 = request.POST.get('time1')
        station2 = request.POST.get('station2')
        time2 = request.POST.get('time2')
        station3 = request.POST.get('station3')
        time3 = request.POST.get('time3')
        station4 = request.POST.get('station4')
        time4 = request.POST.get('time4')
        station5 = request.POST.get('station5')
        time5 = request.POST.get('time5')
        station6 = request.POST.get('station6')
        time6 = request.POST.get('time6')

        data = bus_timetable(bus_name=bus_name, bus_no=bus_number, st_1=station1,
                             t_1=time1, st_2=station2, t_2=time2, st_3=station3, t_3=time3, st_4=station4, t_4=time4, st_5=station5, t_5=time5, st_6=station6, t_6=time6)
        data.save()

        context['success_message'] = 'Data Added'
        return render(request, 'add_data.html', context)

    return render(request, 'add_data.html', context)


@login_required
def admin_logout(request):
    logout(request)
    return render(request, 'login.html')

aduthabus/templates/add_data.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="table">
		<script src="{% static 'js/main.js' %}"></script>

		<div class="add_data_div">
			<button class="logout"><a class="for_a" href="{% url 'bus:admin_logout'%}">Logout</a></button>
			<div class="add_data">
				
				<h1>Add Data</h1>
				<p>{{success_message}}</p>
				<form action="{% url 'bus:add_data'%}" method="POST">
					{% csrf_token %}
		
					<div style="text-align: left;">
						<input type="text" name="bus_name" placeholder="Bus Name" autofocus>
						<br>
						<input type="text" name="bus_number" placeholder="Bus Number">
						<br>
		
						<div>
							<input type="text" name="station1" placeholder="station1">
							<input type="time" name="time1" value="00:00">
						</div>
						<div>
							<input type="text" name="station2" placeholder="station2">
							<input type="time" name="time2" value="00:00">
						</div>
						<div>
							<input type="text" name="station3" placeholder="station3">
							<input type="time" name="time3" value="00:00">
							<button id="btn_add_more" type="button" onclick="add_more()">Add More</button>
						</div>
		
						<div id="add_more">
							<div>
								<input type="text" name="station4" placeholder="station4">
								<input type="time" name="time4" value="00:00">
							</div>
							<div>
								<input type="text" name="station5" placeholder="station5">
								<input type="time" name="time5" value="00:00">
							</div>
							<div>
								<input type="text" name="station6" placeholder="station6">
								<input type="time" name="time6" value="00:00">
							</div>
						</div>
					</div>
		
					<br>
					<button style="text-align: center; font-size: 14px;" type="submit">Save</button>
		
				</form>
			</div>
		</div>
</div>
{% endblock content %}

aduthabus/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="shortcut icon" type="image" href="{% static 'logo_mal.png' %}" />
        <title>ADUTHA_BUS</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>

    <body>
     <div id="full_page">
            {% block content %}
        {% endblock content %}
<div class="footer" align="center">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <div >
            <div class="icon">
                    <a href="#" class="fa fa-facebook"></a>
                
            
                    <a href="#" class="fa fa-instagram"></a>
                
           
                    <a href="#" class="fa fa-twitter"></a>
                
            </div>
            <div>
                
                <h5>Adutha Bus  &copy; 2019</h5>
            </div>
            
        </div>

    
</div>
    
     </div>
    </body>

</html>

aduthabus/templates/bus_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/bus_details.css' %}">
<div class="logo" align="center">
		<img src="{% static 'logo_mal.png' %}" alt="My image" height="150px">
	</div>
{% if bus%}
<table class="container">
	<tr id="bus_name" >
		<th colspan="2"><h1>BUS NAME :    {{bus.bus_name|upper}}</h1></th>
	</tr>
	<tr id="heading">
		<td style="color:black; font-weight:bold;">BUS STAND</td>
		<td style="color:black; font-weight:bold;">TIME</td>

	</tr>
	{% if bus.st_1 %}
	<tr class="row">
		<td>{{bus.st_1|upper}}</td>
		<td>{{bus.t_1|time|upper}}</td>

	</tr>
	{% endif%}
	{% if bus.st_2 %}
	<tr class="row">
		<td>{{bus.st_2|upper}}</td>
		<td>{{bus.t_2|time|upper}}</td>

	</tr>
	{% endif%}
	{% if bus.st_3 %}
	<tr class="row">
		<td>{{bus.st_3|upper}}</td>
		<td>{{bus.t_3|time|upper}}</td>

	</tr>
	{% endif%}
	{% if bus.st_4 %}
	<tr class="row">
		<td>{{bus.st_4|upper}}</td>
		<td>{{bus.t_4|time|upper}}</td>

	</tr>
	{% endif%}
	{% if bus.st_5 %}
	<tr class="row">
		<td>{{bus.st_5|upper}}</td>
		<td>{{bus.t_5|time|upper}}</td>

	</tr>
	{% endif%}
	{% if bus.st_6 %}
	<tr class="row">
		<td>{{bus.st_6|upper}}</td>
		<td>{{bus.t_6|time|upper}}</td>

	</tr>
	{% endif%}
</table>
{% else %}

<p> data is unavilable</p>
{% endif %}




{% endblock content %}

aduthabus/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="home_body">
        <div align="center" class="main_form">

                <div class="logo">
                        <img src="{% static 'logo_mal.png' %}" alt="My image" height="150px">
                    </div>
            
                <form action="{% url 'bus:home_page' %}" method='POST'>
                    {% csrf_token %}
                    {% if unavailable_msg %}
                        <p style="color:red">**{{unavailable_msg}}</p>
                    {% endif %}
                    <!-- <p style="text-align:left">From :</p> -->
                    <input type="text" name="q_source" placeholder="source" autofocus/>
                    <!-- <p style="text-align:left ;left:10px">To :</p> -->
                    <input type="text" name="q_destination" placeholder="destination" />
            
                    <br>
                    <button type="submit" value="get time">Get Time</button>
                </form>
            
            
            </div>
</div>

{% endblock content %}

aduthabus/templates/login.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<div class="home_body">
		<div class="main_form">
				<div class="logo">
                        <img src="{% static 'logo_mal.png' %}" alt="My image" height="150px">
                    </div>
				<h1> Login</h1>
				<br>
				
				<form action="{% url 'bus:admin_login' %}" method="POST">
					{% csrf_token %}
					{% if message %}
					<p style="color:red">**{{message}}</p>
				{% endif %}

					<p><input type="text" name="username" placeholder="admin username" autofocus></p>
					<p><input type="password" name="password" placeholder="password"></p>
					
			<br>
					<button  type="submit">Login</button>
					
				</form>
			</div>
</div>

{% endblock content %}

aduthabus/templates/show_table.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="table">
    <link rel="stylesheet" href="{% static 'css/bus_details.css' %}">

    <div class="logo" align="center">
        <img src="{% static 'logo_mal.png' %}" alt="My image" height="150px">
    </div>
      
      {% if d%}
      <table class="container">
        <tr>
          <th>BUS NAME</th>
          <th>{{s}}</th> 
          <th>{{r}}</th>
        </tr>
      
        {% for i in d  %}
      
         <tr class="row" onclick="window.location='/bus_details/{{i.b_id}}/';">
          <td>{{i.b_name|upper}}</td>
          <td>{{i.s_time|time|upper}}</td> 
          <td>{{i.r_time|time|upper}}</td>
        </tr>
        {% endfor %}
        
        </table>
        {% else %}
      
        <div align="center">
            <h1> data is unavilable</h1>
        </div>
        {% endif %}
      
      
    {% endblock content %}



   
</div>